### ISSUE TITLE
Can revancify v1 and V2 coexist

### ISSUE THREAD

**Issue by B2Pi** [decipher3114/Revancify#122]
With conflicting resources they can't, but I did6n't think it would be a difficult change

**Comment by decipher3114** [comment]
No, and they aren't meant to be. Revancify v2 is a successor and v1 exists only to keep compatibility with RVX. Once the patches are updated, v1 will not be available anymore.

And I can't understand the reason why people keep asking this very same question and don't consider the fact that the apps do work if not updated for 1 year.

Just don't update the apps for 1 month. If you just wait instead of switching back and forth, that would have been much more convenient.
