### ISSUE TITLE
Can't patch Reddit anymore

### ISSUE THREAD

**Issue by notarobot63** [decipher3114/Revancify#80]
Hello

It seems I can't patch Reddit anymore. I'm on Android 14 with LineageOS and MicroG using Termux.

Here is the log:

[patch_log.txt](https://github.com/decipher3114/Revancify/files/15206712/patch_log.txt)

**Comment by Xisrr1** [comment]
Version 2024.18.0+ won't work in the near future.

**Comment by Xisrr1** [comment]
> > Versions 2024.18.0+ won't work in the near future. 
> 
> Any more info on this? Any posts or explanation?

https://github.com/ReVanced/revanced-patches/issues/3099

**Comment by juandvasquezp** [comment]
For inotia00 's patch there's the possibility to implement their ARSCLib implementation explained here:

https://github.com/inotia00/revanced-documentation/blob/main/docs/latest-reddit-patch-info.md

Only thing needed is to configure so that reddit versions over 2024.17.0 will use the custom ARSCLib CLI and Patches files.
